#!/usr/bin/env python
#Created by Wheeler Gans

import os
import sys
import datetime as dt
import serial

def logline():
    line = ser.readline()
    if 'ERROR' in line.decode():
        errorfile.write(line.decode())
    outfile.write(line.decode())
    print(line.decode().rstrip())

if __name__ == '__main__':
    name = input("Type name of USB device: ")
    device_name = input("enter device id: ")

    outfile_name = device_name + '_' + str(dt.datetime.now().month) + '_' + str(dt.datetime.now().day)
    errorfile_name = device_name + '_' + str(dt.datetime.now().month) + '_' + str(dt.datetime.now().day)+'_ERR'
    outfile = open(outfile_name, 'w',100)
    errorfile = open(errorfile_name,'w',1)
    outfile.write("Device ID: ")
    outfile.write(device_name + '\n')
    outfile.write("Start Time: ")
    outfile.write(str(dt.datetime.now())+ '\n')
    outfile.write("\n")
    outfile.write("\n")
    outfile.write("\n")

    addr = "/dev/"+name
    baud = 57600 ## baud rate for instrument

    ser = serial.Serial(port = addr,baudrate = baud,timeout=10)

    print("Connected to: " + ser.portstr)
    ser.flush()
    try:
        while True:
            logline()
            print("User Input: ", end = '')
            print(sys.stdin.readline())

    except KeyboardInterrupt:
        outfile.write("End Time: ")
        outfile.write(str(dt.datetime.now())+ '\n')
        outfile.close()
        errorfile.close()

